/**
 * European (single-zero) roulette table data and payouts (CLAUDE.md §7).
 *
 * One green zero + 1..36 → 37 pockets. The house edge is INHERENT in the wheel,
 * not a config knob: every bet pays its "fair" price for a 36-pocket wheel
 * (total return = 36 / numbersCovered), but there are 37 pockets, so the
 * realized RTP is 36/37 ≈ 97.30% (a 2.70% edge) on every bet. That is exactly
 * what makes single-zero roulette single-zero — so there is no per-bet vig to
 * configure here, unlike the build-a-table games (Wheel/Keno).
 */

/** Pockets on the wheel: 0..36. */
export const POCKETS = 37

/**
 * The physical European wheel sequence, starting at 0. Presentation only — the
 * winning pocket is drawn uniformly (fair.ts); this just lays the disc out so
 * the spin animation lands a real wheel order under the pointer.
 */
export const WHEEL_ORDER = [
  0, 32, 15, 19, 4, 21, 2, 25, 17, 34, 6, 27, 13, 36, 11, 30, 8, 23, 10, 5, 24, 16, 33, 1, 20, 14,
  31, 9, 22, 18, 29, 7, 28, 12, 35, 3, 26,
] as const

/** The red numbers on a European wheel; everything else (bar 0) is black. */
export const RED_NUMBERS = new Set([
  1, 3, 5, 7, 9, 12, 14, 16, 18, 19, 21, 23, 25, 27, 30, 32, 34, 36,
])

export type PocketColor = 'green' | 'red' | 'black'

/** The colour of a pocket: 0 is green, the rest split red/black. */
export function colorOf(n: number): PocketColor {
  if (n === 0) return 'green'
  return RED_NUMBERS.has(n) ? 'red' : 'black'
}

/** Total return on a winning bet covering `count` numbers: 36 / count (the
 *  classic fair price — e.g. a straight-up on 1 number returns 36×, "35 to 1"). */
export function payoutFor(count: number): number {
  if (!Number.isInteger(count) || count < 1 || count > 36) {
    throw new Error(`a bet must cover 1..36 numbers, got ${count}`)
  }
  return 36 / count
}

/* ----------------------- standard outside/group bets ----------------------- */

/** The numbers in a given column (1 = bottom row 1,4,7…; etc.). */
export function column(which: 1 | 2 | 3): number[] {
  return Array.from({ length: 12 }, (_, i) => which + i * 3)
}

/** The numbers in a given dozen (1 = 1–12, 2 = 13–24, 3 = 25–36). */
export function dozen(which: 1 | 2 | 3): number[] {
  const start = (which - 1) * 12 + 1
  return Array.from({ length: 12 }, (_, i) => start + i)
}

/** A bet the table can place: the numbers it covers + a human label. The stake
 *  is held separately (UI side), so this stays a pure description of the wager. */
export interface BetSpot {
  id: string
  label: string
  numbers: number[]
}

const range = (a: number, b: number) => Array.from({ length: b - a + 1 }, (_, i) => a + i)
const evens = range(1, 36).filter((n) => n % 2 === 0)
const odds = range(1, 36).filter((n) => n % 2 === 1)

/** The standard outside bets, in display order. Inside (straight-up) spots for
 *  each number 0..36 are generated by the board itself. */
export const OUTSIDE_BETS: BetSpot[] = [
  { id: 'low', label: '1–18', numbers: range(1, 18) },
  { id: 'even', label: 'Even', numbers: evens },
  { id: 'red', label: 'Red', numbers: [...RED_NUMBERS] },
  { id: 'black', label: 'Black', numbers: range(1, 36).filter((n) => !RED_NUMBERS.has(n)) },
  { id: 'odd', label: 'Odd', numbers: odds },
  { id: 'high', label: '19–36', numbers: range(19, 36) },
  { id: 'dozen1', label: '1st 12', numbers: dozen(1) },
  { id: 'dozen2', label: '2nd 12', numbers: dozen(2) },
  { id: 'dozen3', label: '3rd 12', numbers: dozen(3) },
  { id: 'col1', label: 'Col 1', numbers: column(1) },
  { id: 'col2', label: 'Col 2', numbers: column(2) },
  { id: 'col3', label: 'Col 3', numbers: column(3) },
]

/** Look up a bet spot's covered numbers + label by its id (number ids are `n7`). */
export function spotFor(id: string): BetSpot {
  if (id.startsWith('n')) {
    const n = Number(id.slice(1))
    return { id, label: String(n), numbers: [n] }
  }
  const found = OUTSIDE_BETS.find((b) => b.id === id)
  if (!found) throw new Error(`unknown bet spot ${id}`)
  return found
}
